### ISSUE TITLE
The advanced testing link isn't working

### ISSUE THREAD

**Issue by cassianotartari** [DannyDainton/post-con-2019-workshop#1]
I tried to import the collection without success, can you please check if the links are ok? Thanks

**Comment by mccannt** [comment]
@cassianotartari You are right. Give us a bit, we will get it fixed up. 
Thanks for pointing that out.

**Comment by DannyDainton** [comment]
My bad  @cassianotartari :( 

I killed a Workspace on one of my accounts by mistake.

You can also do a direct import into your app with these files from the repo:

https://github.com/DannyDainton/post-con-2019-workshop/tree/master/Assets/Collections

**Comment by cassianotartari** [comment]
Thank you, using https://raw.githubusercontent.com/DannyDainton/post-con-2019-workshop/master/Assets/Collections/Testing_Module_POSTCON2019.postman_collection.json in the import from link worked!
